/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppAgentsRouteImport } from './routes/app.agents'
import { Route as AppAnalyticsRouteImport } from './routes/app.analytics'
import { Route as AppCacheRouteImport } from './routes/app.cache'
import { Route as AppHealthRouteImport } from './routes/app.health'
import { Route as AppKeysRouteImport } from './routes/app.keys'
import { Route as AppLabsRouteImport } from './routes/app.labs'
import { Route as AppLogsRouteImport } from './routes/app.logs'
import { Route as AppMembersRouteImport } from './routes/app.members'
import { Route as AppModelsRouteImport } from './routes/app.models'
import { Route as AppProvidersRouteImport } from './routes/app.providers'
import { Route as AppRagRouteImport } from './routes/app.rag'
import { Route as AppRoutingRouteImport } from './routes/app.routing'
import { Route as AppSandboxRouteImport } from './routes/app.sandbox'
import { Route as AppSecurityRouteImport } from './routes/app.security'
import { Route as AppTeamLogsRouteImport } from './routes/app.team-logs'
import { Route as AppTeamsRouteImport } from './routes/app.teams'
import { Route as AppInspectUserIdRouteImport } from './routes/app.inspect.$userId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAgentsRoute = AppAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppCacheRoute = AppCacheRouteImport.update({
  id: '/cache',
  path: '/cache',
  getParentRoute: () => AppRoute,
} as any)
const AppHealthRoute = AppHealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => AppRoute,
} as any)
const AppKeysRoute = AppKeysRouteImport.update({
  id: '/keys',
  path: '/keys',
  getParentRoute: () => AppRoute,
} as any)
const AppLabsRoute = AppLabsRouteImport.update({
  id: '/labs',
  path: '/labs',
  getParentRoute: () => AppRoute,
} as any)
const AppLogsRoute = AppLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AppRoute,
} as any)
const AppMembersRoute = AppMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AppRoute,
} as any)
const AppModelsRoute = AppModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => AppRoute,
} as any)
const AppProvidersRoute = AppProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => AppRoute,
} as any)
const AppRagRoute = AppRagRouteImport.update({
  id: '/rag',
  path: '/rag',
  getParentRoute: () => AppRoute,
} as any)
const AppRoutingRoute = AppRoutingRouteImport.update({
  id: '/routing',
  path: '/routing',
  getParentRoute: () => AppRoute,
} as any)
const AppSandboxRoute = AppSandboxRouteImport.update({
  id: '/sandbox',
  path: '/sandbox',
  getParentRoute: () => AppRoute,
} as any)
const AppSecurityRoute = AppSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AppRoute,
} as any)
const AppTeamLogsRoute = AppTeamLogsRouteImport.update({
  id: '/team-logs',
  path: '/team-logs',
  getParentRoute: () => AppRoute,
} as any)
const AppTeamsRoute = AppTeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => AppRoute,
} as any)
const AppInspectUserIdRoute = AppInspectUserIdRouteImport.update({
  id: '/inspect/$userId',
  path: '/inspect/$userId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/app/agents': typeof AppAgentsRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/cache': typeof AppCacheRoute
  '/app/health': typeof AppHealthRoute
  '/app/keys': typeof AppKeysRoute
  '/app/labs': typeof AppLabsRoute
  '/app/logs': typeof AppLogsRoute
  '/app/members': typeof AppMembersRoute
  '/app/models': typeof AppModelsRoute
  '/app/providers': typeof AppProvidersRoute
  '/app/rag': typeof AppRagRoute
  '/app/routing': typeof AppRoutingRoute
  '/app/sandbox': typeof AppSandboxRoute
  '/app/security': typeof AppSecurityRoute
  '/app/team-logs': typeof AppTeamLogsRoute
  '/app/teams': typeof AppTeamsRoute
  '/app/': typeof AppIndexRoute
  '/app/inspect/$userId': typeof AppInspectUserIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/app/agents': typeof AppAgentsRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/cache': typeof AppCacheRoute
  '/app/health': typeof AppHealthRoute
  '/app/keys': typeof AppKeysRoute
  '/app/labs': typeof AppLabsRoute
  '/app/logs': typeof AppLogsRoute
  '/app/members': typeof AppMembersRoute
  '/app/models': typeof AppModelsRoute
  '/app/providers': typeof AppProvidersRoute
  '/app/rag': typeof AppRagRoute
  '/app/routing': typeof AppRoutingRoute
  '/app/sandbox': typeof AppSandboxRoute
  '/app/security': typeof AppSecurityRoute
  '/app/team-logs': typeof AppTeamLogsRoute
  '/app/teams': typeof AppTeamsRoute
  '/app': typeof AppIndexRoute
  '/app/inspect/$userId': typeof AppInspectUserIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/app/agents': typeof AppAgentsRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/cache': typeof AppCacheRoute
  '/app/health': typeof AppHealthRoute
  '/app/keys': typeof AppKeysRoute
  '/app/labs': typeof AppLabsRoute
  '/app/logs': typeof AppLogsRoute
  '/app/members': typeof AppMembersRoute
  '/app/models': typeof AppModelsRoute
  '/app/providers': typeof AppProvidersRoute
  '/app/rag': typeof AppRagRoute
  '/app/routing': typeof AppRoutingRoute
  '/app/sandbox': typeof AppSandboxRoute
  '/app/security': typeof AppSecurityRoute
  '/app/team-logs': typeof AppTeamLogsRoute
  '/app/teams': typeof AppTeamsRoute
  '/app/': typeof AppIndexRoute
  '/app/inspect/$userId': typeof AppInspectUserIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/onboarding'
    | '/app/agents'
    | '/app/analytics'
    | '/app/cache'
    | '/app/health'
    | '/app/keys'
    | '/app/labs'
    | '/app/logs'
    | '/app/members'
    | '/app/models'
    | '/app/providers'
    | '/app/rag'
    | '/app/routing'
    | '/app/sandbox'
    | '/app/security'
    | '/app/team-logs'
    | '/app/teams'
    | '/app/'
    | '/app/inspect/$userId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/onboarding'
    | '/app/agents'
    | '/app/analytics'
    | '/app/cache'
    | '/app/health'
    | '/app/keys'
    | '/app/labs'
    | '/app/logs'
    | '/app/members'
    | '/app/models'
    | '/app/providers'
    | '/app/rag'
    | '/app/routing'
    | '/app/sandbox'
    | '/app/security'
    | '/app/team-logs'
    | '/app/teams'
    | '/app'
    | '/app/inspect/$userId'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/onboarding'
    | '/app/agents'
    | '/app/analytics'
    | '/app/cache'
    | '/app/health'
    | '/app/keys'
    | '/app/labs'
    | '/app/logs'
    | '/app/members'
    | '/app/models'
    | '/app/providers'
    | '/app/rag'
    | '/app/routing'
    | '/app/sandbox'
    | '/app/security'
    | '/app/team-logs'
    | '/app/teams'
    | '/app/'
    | '/app/inspect/$userId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/agents': {
      id: '/app/agents'
      path: '/agents'
      fullPath: '/app/agents'
      preLoaderRoute: typeof AppAgentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/analytics': {
      id: '/app/analytics'
      path: '/analytics'
      fullPath: '/app/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/cache': {
      id: '/app/cache'
      path: '/cache'
      fullPath: '/app/cache'
      preLoaderRoute: typeof AppCacheRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/health': {
      id: '/app/health'
      path: '/health'
      fullPath: '/app/health'
      preLoaderRoute: typeof AppHealthRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/keys': {
      id: '/app/keys'
      path: '/keys'
      fullPath: '/app/keys'
      preLoaderRoute: typeof AppKeysRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/labs': {
      id: '/app/labs'
      path: '/labs'
      fullPath: '/app/labs'
      preLoaderRoute: typeof AppLabsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/logs': {
      id: '/app/logs'
      path: '/logs'
      fullPath: '/app/logs'
      preLoaderRoute: typeof AppLogsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/members': {
      id: '/app/members'
      path: '/members'
      fullPath: '/app/members'
      preLoaderRoute: typeof AppMembersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/models': {
      id: '/app/models'
      path: '/models'
      fullPath: '/app/models'
      preLoaderRoute: typeof AppModelsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/providers': {
      id: '/app/providers'
      path: '/providers'
      fullPath: '/app/providers'
      preLoaderRoute: typeof AppProvidersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/rag': {
      id: '/app/rag'
      path: '/rag'
      fullPath: '/app/rag'
      preLoaderRoute: typeof AppRagRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/routing': {
      id: '/app/routing'
      path: '/routing'
      fullPath: '/app/routing'
      preLoaderRoute: typeof AppRoutingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/sandbox': {
      id: '/app/sandbox'
      path: '/sandbox'
      fullPath: '/app/sandbox'
      preLoaderRoute: typeof AppSandboxRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/security': {
      id: '/app/security'
      path: '/security'
      fullPath: '/app/security'
      preLoaderRoute: typeof AppSecurityRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/team-logs': {
      id: '/app/team-logs'
      path: '/team-logs'
      fullPath: '/app/team-logs'
      preLoaderRoute: typeof AppTeamLogsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/teams': {
      id: '/app/teams'
      path: '/teams'
      fullPath: '/app/teams'
      preLoaderRoute: typeof AppTeamsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/inspect/$userId': {
      id: '/app/inspect/$userId'
      path: '/inspect/$userId'
      fullPath: '/app/inspect/$userId'
      preLoaderRoute: typeof AppInspectUserIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAgentsRoute: typeof AppAgentsRoute
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppCacheRoute: typeof AppCacheRoute
  AppHealthRoute: typeof AppHealthRoute
  AppKeysRoute: typeof AppKeysRoute
  AppLabsRoute: typeof AppLabsRoute
  AppLogsRoute: typeof AppLogsRoute
  AppMembersRoute: typeof AppMembersRoute
  AppModelsRoute: typeof AppModelsRoute
  AppProvidersRoute: typeof AppProvidersRoute
  AppRagRoute: typeof AppRagRoute
  AppRoutingRoute: typeof AppRoutingRoute
  AppSandboxRoute: typeof AppSandboxRoute
  AppSecurityRoute: typeof AppSecurityRoute
  AppTeamLogsRoute: typeof AppTeamLogsRoute
  AppTeamsRoute: typeof AppTeamsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppInspectUserIdRoute: typeof AppInspectUserIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAgentsRoute: AppAgentsRoute,
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppCacheRoute: AppCacheRoute,
  AppHealthRoute: AppHealthRoute,
  AppKeysRoute: AppKeysRoute,
  AppLabsRoute: AppLabsRoute,
  AppLogsRoute: AppLogsRoute,
  AppMembersRoute: AppMembersRoute,
  AppModelsRoute: AppModelsRoute,
  AppProvidersRoute: AppProvidersRoute,
  AppRagRoute: AppRagRoute,
  AppRoutingRoute: AppRoutingRoute,
  AppSandboxRoute: AppSandboxRoute,
  AppSecurityRoute: AppSecurityRoute,
  AppTeamLogsRoute: AppTeamLogsRoute,
  AppTeamsRoute: AppTeamsRoute,
  AppIndexRoute: AppIndexRoute,
  AppInspectUserIdRoute: AppInspectUserIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
